//LOCALHOST
### Get all contacts info
GET http://localhost:8080/contacts HTTP/1.1

### Get single contact by Id (Esther)
GET http://localhost:8080/contacts/65a2e43d48acf6d0d3e9969e HTTP/1.1

### (Egoyibo)
GET http://localhost:8080/contacts/65a2e48348acf6d0d3e9969f HTTP/1.1

### (Jane)
GET http://localhost:8080/contacts/65a2e4b548acf6d0d3e996a0 HTTP/1.1

### (Margaret)
GET http://localhost:8080/contacts/65a2e4e048acf6d0d3e996a1 HTTP/1.1

### (Luka)
GET http://localhost:8080/contacts/65a2e4f148acf6d0d3e996a2 HTTP/1.1


### Create new contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Boyd",
    "lastName": "Parker",
    "email": "Parker.boyd@churchofjesuschrist.org",
    "favoriteColor": "White",
    "birthday": "09/22/1903"
}

### Update contact info (Margaret Id)
PUT http://localhost:8080/contacts/65a2e4e048acf6d0d3e996a1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Magaret",
    "lastName": "Minchakpu",
    "email": "Maggie112@yahoo.com",
    "favoriteColor": "Gray",
    "birthday": "05/10/2009"
}

### Delete contact info (Luka Ebega)
DELETE http://localhost:8080/contacts/65ac0d1e6c6a0a5f85f9d811 HTTP/1.1

//Render
### Get all Contacts
GET https://project1-part1.onrender.com/contacts/ HTTP/1.1

### Get contact based on ID (Esther)
GET https://project1-part1.onrender.com/contacts/65a2e43d48acf6d0d3e9969e HTTP/1.1

### (Egoyibo)
GEThttps://project1-part1.onrender.com/contacts/65a2e48348acf6d0d3e9969f HTTP/1.1

### (Jane)
GET https://project1-part1.onrender.com/contacts/65a2e4b548acf6d0d3e996a0 HTTP/1.1

### (Margaret)
GET https://project1-part1.onrender.com/contacts/65a2e4e048acf6d0d3e996a1 HTTP/1.1

### (Luka)
GET https://project1-part1.onrender.com/contacts/65a2e4f148acf6d0d3e996a2 HTTP/1.1



### Create new contact
POST https://project1-part1.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Rusell",
    "lastName": "Nelson",
    "email": "prophet.seer@churchofjesuschrist.org",
    "favoriteColor": "White",
    "birthday": "11/23/1902"
}

### Update contact info (Jane)
PUT https://project1-part1.onrender.com/contacts/65a2e4b548acf6d0d3e996a0 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Janet",
    "lastName": "Ojochide",
    "email": "ojochide.jenny@happinesscomputers.com",
    "favoriteColor": "Slate green",
    "birthday": "12/27/1981"
}

### Delete contact
DELETE https://project1-part1.onrender.com/contacts/65a2e48348acf6d0d3e9969f HTTP/1.1
